### PR TITLE
Dask name fix

### PR DESCRIPTION
**Pull request by d-v-b**
- add examples to the front page of the docs
- add tests for `zarr_array_from_dask`, and add correct behavior
- bump cellmap-schemas to 0.2.0
- add a few type hints
- fix `get_url` behavior for fsstores with multiple protocols (e.g., s3)
- doctrings

@neptunes5thmoon the fix for the xarray naming is buried in here along with a lot of other stuff

### CODE REVIEW

**Comment by d-v-b** [comment]
re: xarray naming, I made two choices: 

- the name of the xarray.DataArray is still the basename of the input zarr array. I could also imagine this being the path fragment after the root of the container, e.g. for an array at `file://foo.zarr/path/to/array`, the name would be `path/to/array`, where in this PR it would just be `array`. Let me know if you have a preference.

- the dask array's name is now `<url>-<hash>`, where `url` is the result of calling `fibsem_tools.io.zarr.get_url` on the array, so the dask array would would be named something like `s3://path/to/zarr.zarr/path/to/array-blablabla`. This is both unique and human readable, so I think it should be OK.

**Comment by neptunes5thmoon** [comment]
I generally agree with your choices. For the name of the data array I think I'd prefer the `path/to/array` option.

I wonder whether there's a use case for users to specify the dask array's name themselves since that's no longer an option now?

**Comment by d-v-b** [comment]
[`to_dask`](https://github.com/janelia-cellmap/fibsem-tools/blob/f98053e3db01c241f535c1f5d6828f1b582fe642/src/fibsem_tools/io/zarr.py#L282) forwards `name` to `da.from_array` via `**kwargs` (and [`to_xarray`](https://github.com/janelia-cellmap/fibsem-tools/blob/f98053e3db01c241f535c1f5d6828f1b582fe642/src/fibsem_tools/io/zarr.py#L497C29-L497C29)  forwards `name` to `to_dask`), so users can still set the name if they want

**Comment by d-v-b** [comment]
> For the name of the data array I think I'd prefer the path/to/array option.

me too, i'm going to change that accordingly

**Comment by neptunes5thmoon** [comment]
I might have missed something, but I thought you'd have to keep forwarding `name` [here](https://github.com/janelia-cellmap/fibsem-tools/blame/f98053e3db01c241f535c1f5d6828f1b582fe642/src/fibsem_tools/io/zarr.py#L579)

**Comment by d-v-b** [comment]
> I might have missed something, but I thought you'd have to keep forwarding name [here](https://github.com/janelia-cellmap/fibsem-tools/blame/f98053e3db01c241f535c1f5d6828f1b582fe642/src/fibsem_tools/io/zarr.py#L579)

oops, this clearly needs a test :)

**Comment by d-v-b** [comment]
also, i think we have to go back to `(array | group).basename` for the default name for the `DataArray | DataTree`, since `DataTree` instances can't contain nodes with names that contain the "/" character

**Comment by d-v-b** [comment]
> If we do let the user set it we might wanna disentangle the two names since they don't have the same purpose...

Yep. As you suggest, I'm decoupling the two `name`s. The dask array will have the name `<array url>-hash`, which is a little redundant because the dask hash already includes the array url in the hash, but this is a bit more readable. This `name` parameter is not settable from `read_xarray`. 

The `name` for the `xarray.DataArray` will be settable from the `name` kwarg in `read_xarray`; this kwarg defaults to `None`, in which case the `basename` of the zarr array is used (this was the only way to appease the demands of `DataTree`, which requires that node names do not contain `/`.

**Pull request merged**
